<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVmLJ0Ya\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVmLJ0Ya/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVmLJ0Ya.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVmLJ0Ya\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVmLJ0Ya\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VmLJ0Ya',
    'container.build_id' => '8a5db548',
    'container.build_time' => 1554376676,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVmLJ0Ya');
